services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: consultorio_backend_container
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend/consultorio
    container_name: consultorio_frontend_container
    ports:
      - "3000:3000"

volumes:
  pgdata:
